name: gma_news_unofficial
author: hush2
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  http: ^0.12.0+2
  flutter_html: ^0.9.6
  font_awesome_flutter: ^8.4.0
  url_launcher: ^5.0.2
  cached_network_image: ^0.7.0
  flutter_cache_manager: ^0.3.2
  timeago: ^2.0.14

flutter:
  uses-material-design: true
